# Generated by Django 3.0.2 on 2020-01-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
