# Generated by Django 3.0.2 on 2020-01-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200122_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(max_length=512, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=10, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.TextField(choices=[('ACTIVE', 'Активно'), ('HIDDEN', 'Скрыто'), ('DELETED', 'Удалено')], default='ACTIVE', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='Файл'),
        ),
    ]
