# Generated by Django 3.0.2 on 2020-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200123_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='search',
            name='matches',
            field=models.ManyToManyField(related_name='searches', related_query_name='search', to='main.Car'),
        ),
        migrations.AddField(
            model_name='search',
            name='search_value',
            field=models.CharField(default='', max_length=32, verbose_name='Строка поиска'),
            preserve_default=False,
        ),
    ]
