# Generated by Django 3.0.2 on 2020-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='geo',
        ),
    ]
